sudo: false
language: c

addons:
  apt:
    packages:
    - libssl-dev

install:
  - make SECURE_COMPARATOR=enable
#  - make SECURE_COMPARATOR=enable install
  - make SECURE_COMPARATOR=enable test

script:
  - LD_LIBRARY_PATH=build build/tests/soter_test
  - LD_LIBRARY_PATH=build build/tests/themis_test