sudo: required
language: c

addons:
  apt:
    packages:
    - libssl-dev

install:
  - make SECURE_COMPARATOR=enable
  - sudo make SECURE_COMPARATOR=enable install
  - make SECURE_COMPARATOR=enable test

script:
  - build/tests/soter_test
  - build/tests/themis_test