sudo: false
language: c

addons:
  apt:
    packages:
    - openssl
    - libssl-dev

install:
  - make SECURE_COMPARATOR=enable
  #- make SECYRE_COMPARATOR=enable PREFIX=~ install
  - make SECURE_COMPARATOR=enable test

script:
  - LD_LIBRARY_PATH=build build/tests/soter_test
  - LD_LIBRARY_PATH=build build/tests/themis_test